### ISSUE TITLE
发现遗传算法得到的参数带回去验证时，策略的统计结果与对应遗传算法的统计结果有明显差异

### ISSUE THREAD

**Issue by yxl560** [vnpy/vnpy_ctabacktester#16]
操作系统: 如Windows 11
Python版本: 如VeighNa Studio-3.2

过程描述：
        先使用遗传算法（品种、精度统一）跑出参数A,把参数A带回去，使用单进程跑策略得到的策略统计结果与遗传算法得到的统计结果有显示差异。
![1c4db2be92f096ad96ddb8a2152f022](https://user-images.githubusercontent.com/57986593/179329184-e91b5786-f0fe-43f3-b05f-720981e66915.png)  表格数据就是遗传算法导出的对应参数的策略统计的数据。

**Comment by Edanflame** [comment]
总交易日和交易笔数是一样的，说明交易的逻辑应该是一样的，但关于资金的结果不一样，是不是两者手续费、交易滑点、合约乘数不一致

**Comment by yxl560** [comment]
不是写的非常清楚，同参数情况下，使用交易所的品种精度和统一滑的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月18日(周一) 上午9:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vnpy/vnpy_ctabacktester] 发现遗传算法得到的参数带回去验证时，策略的统计结果与对应遗传算法的统计结果有明显差异 (Issue #16)




 
总交易日和交易笔数是一样的，说明交易的逻辑应该是一样的，但关于资金的结果不一样，是不是两者手续费、交易滑点、合约乘数不一致

**Comment by yxl560** [comment]
这个问题，同时存在于投资组合模块和Cta模块



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月18日(周一) 上午9:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vnpy/vnpy_ctabacktester] 发现遗传算法得到的参数带回去验证时，策略的统计结果与对应遗传算法的统计结果有明显差异 (Issue #16)




 
总交易日和交易笔数是一样的，说明交易的逻辑应该是一样的，但关于资金的结果不一样，是不是两者手续费、交易滑点、合约乘数不一致

**Comment by Edanflame** [comment]
请问是个别的策略中个别参数组合会出现问题，还是遗传算法的所有结果都是有问题的。
我这边使用vnpy/examples/cta_backtesting/backtesting_demo进行遗传算法优化，标的物使用的是股指期货，策略使用AtrRsiStrategy。使用遗传算法的尝试的结果在ui中的vnpy_ctabacktest中进行回测，数值都是一样的。麻烦试一下使用backtesting_demo进行优化，方便排除一下是否与策略或数据有关。
