### ISSUE TITLE
希望增加几个回测指标

### ISSUE THREAD

**Issue by easibay** [vnpy/vnpy_ctabacktester#18]
实盘中，有两个回撤指标特别受关注
1、最长回撤时间
2、最大回撤对应的恢复时间
看是否有时间添加

另外，cta的单独回测或者组合回测的时候，能否显示仓位的杠杆率水平（或者仓位水平），时序的或者最大的杠杆率（仓位）

**Comment by vnpy** [comment]
扩展统计指标这块，可以通过calculate_result后返回的每日盈亏情况的DataFrame进行计算实现。
