### ISSUE TITLE
回测k线图表 数据量多了后拖动很卡， 建议进行显示内存优化

### ISSUE THREAD

**Issue by smccjjj** [vnpy/vnpy_ctabacktester#19]
环境
操作系统: 如Windows 11
Python版本: 3.7
VeighNa版本: 3.3.0
Issue类型
三选一：Enhancement

预期程序行为
拖动不卡，流畅拖动，

实际程序行为
实际行为： 导入10年1分钟的数据大概50w条，拖一下卡半天，卡得电脑都动不了。建议进行大数据量下的内存优化。

重现步骤
![微信截图_20220923151947](https://user-images.githubusercontent.com/83157082/191911639-11def201-4ef5-4aa3-870b-49f52e597182.png)

**Comment by vnpy** [comment]
这里初始加载时的卡顿，由于大量K线的绘制工作导致，没有太好的处理办法。

考虑到是回测结果的显示场景，因此这里暂时不进行单独处理。
