### ISSUE TITLE
50w数据量 点击回测  回放数据大概要30分钟 而且不能ui卡住 不能动弹，这个能优化下吗 缩短时间

### ISSUE THREAD

**Issue by smccjjj** [vnpy/vnpy_ctabacktester#20]
环境
操作系统: 如Windows 10   8G 内存  10400F的cpu  显卡1080ti
Python版本: 3.7
VeighNa版本: 3.3.0
Issue类型
三选一：Enhancement

预期程序行为
回放速度正常，UI不被卡住。

实际程序行为
实际行为： 50w数据量 点击回测  回放数据大概要30分钟 而且不能ui卡住 不能动弹，这个能优化下吗 缩短时间。UI不会被卡住啊

重现步骤
大概50w数据量  点击-开始回测 等待数据导入-等待数据回放 （因为数据量太大，卡住了 鼠标转圈，UI不能动）

**Comment by noranhe** [comment]
请问多次尝试都是这样的吗？我们这边8G的机器用mysql数据库十年七十多万条数据测下来不到两分钟的。正常情况下不应该需要半个小时的
